// src/lib/fonts.ts
import localFont from "next/font/local";

/**
 * Single typeface for the whole site: Montserrat, variable, latin subset, self-hosted.
 * Montserrat is a deliberate choice by the owner of the site, for body copy as well as for
 * headings: there is one family here and no second "display" face.
 *
 * WHERE THE FILE COMES FROM
 * The .woff2 is the "latin" subset Google Fonts serves for
 * https://fonts.googleapis.com/css2?family=Montserrat:wght@100..900&display=swap — downloaded
 * once, by hand, and committed. The Google loader of `next/font` is deliberately NOT used: it
 * hits the network on every build (CI and Vercel) and self-hosts the result anyway, so it would
 * only add an external point of failure. Nothing in src/ may import it, and the repo greps for
 * that import path as a hard guard — which is why this comment does not spell it out verbatim.
 * The price is that the file is versioned in the repo and has to be regenerated by hand when
 * Montserrat is bumped; the whole procedure, including the pyftsubset command and the .ttf
 * twin, lives in scripts/prepare-fonts.md.
 *
 * LICENSE
 * Montserrat is distributed under the SIL Open Font License 1.1, which REQUIRES the license
 * text to travel with the font files. It is checked in as src/lib/assets/fonts/OFL.txt, next to
 * the fonts; it must never be deleted or moved away from them. src/lib/fonts.test.ts fails if
 * it disappears.
 *
 * THE .ttf TWIN
 * src/lib/assets/fonts/Montserrat-Variable.ttf (745 KB, the full family, not the subset) is
 * NEVER served to the browser and is not referenced from here. It exists only because satori —
 * the renderer behind next/og — cannot parse WOFF2 and has to be handed a TTF buffer. §11
 * (opengraph-image) reads it with readFile at build time.
 *
 * NAME-TABLE CAVEAT
 * The file declares "Montserrat Thin" in nameID 1, because in Google's variable builds the
 * default instance is wght=100. That name is irrelevant to what the browser sees — next/font
 * generates the family from this call — but it does have one consequence, see adjustFontFallback.
 */

/**
 * CONTRACT — read before writing the layout (§8.4) or touching globals.css.
 *
 *  1. The export is `sans`, not `montserrat`: it is the neutral role name, so the next change
 *     of typeface touches this file and nothing else.
 *  2. Somebody has to `import { sans } from "@/lib/fonts"` and put `sans.variable` on <html>.
 *     src/app/layout.tsx already does; phase 2 rewrites that file and must keep both. This is
 *     not styling sugar: the import is what pulls this module into the compiled graph, and
 *     without it next/font/local never runs — no @font-face, no .woff2 in .next, and
 *     --font-montserrat declared nowhere. `find .next -iname "*.woff2"` after a build is the
 *     cheap way to prove it is still wired.
 *  3. The CSS variable is --font-montserrat. globals.css must read
 *     `--font-sans: var(--font-montserrat, ui-sans-serif), …` in its @theme block; it was
 *     renamed together with the typeface, so any other --font-* name left in that file is
 *     stale. If the two names drift apart nothing throws: the site quietly drops to the system
 *     stack, and only because of that in-var fallback — without it an undefined
 *     --font-montserrat invalidates the whole --font-sans value, reserve list included, and
 *     <body> inherits the initial font-family, i.e. Times New Roman. Grep for both names after
 *     any font change.
 */
export const sans = localFont({
  src: [
    { path: "./assets/fonts/Montserrat-Variable-latin.woff2", weight: "100 900", style: "normal" },
  ],
  // The real axis of the file is wght 100–900 and it is declared in full: with
  // `font-synthesis-weight: none` in globals.css (§9) the browser clamps anything outside the
  // declared range instead of faking it, so under-declaring the axis would silently flatten a
  // weight rather than render it. Which weights the design actually uses is decided by the
  // typography tokens in globals.css (they stop at 600), not here.
  //
  // NOT --font-sans. next/font declares the variable on <html>, the same element and the same
  // specificity (0,1,0) where Tailwind emits its `:root { --font-sans: … }`; which one won
  // would depend on CSS injection order, which Next does not guarantee. With a distinct name,
  // `--font-sans: var(--font-montserrat), …` in globals.css is a chain, not a cycle.
  variable: "--font-montserrat",
  // Text paints with the fallback immediately and the LCP does not wait for the font.
  // With `optional` many first-time visitors would never see Montserrat at all.
  display: "swap",
  // It is the only family on the site, so preloading it is correct.
  preload: true,
  // This is what kills font CLS, and it is recalculated for Montserrat by construction: for a
  // LOCAL font Next runs fontkit over the actual file on disk (getFallbackMetricsFromFontFile)
  // and emits a fallback @font-face with src: local(Arial) plus size-adjust, ascent-override,
  // descent-override and line-gap-override. No metric of the previous typeface survives here,
  // and none is hardcoded: the numbers below are what the file itself yields.
  //
  // Montserrat's real metrics (hhea and OS/2 of the committed file, identical to Next's own
  // capsize table): ascent 968, descent -251, lineGap 0, unitsPerEm 1000, xWidthAvg 503 — an
  // average glyph width of 0.503 em, wider than most of the usual sans fallbacks, which is
  // precisely why reusing someone else's overrides would show up as a layout jump.
  //
  // What Next will emit for this file: size-adjust 110.19%, ascent-override 87.85%,
  // descent-override 22.78%, line-gap-override 0.00%. Caveat worth knowing: fontkit measures
  // the advance widths of the file's DEFAULT instance, which is wght=100 here (see the
  // name-table caveat above), so the fallback is tuned ~3% narrower than Montserrat 400 —
  // 113.90% would be the ideal size-adjust for body copy. The residual is small and there is no
  // option in next/font/local to override it; correcting it would mean adjustFontFallback:false
  // plus a hand-written fallback @font-face in globals.css, which is not worth the extra rule.
  adjustFontFallback: "Arial",
  // The stack used until Montserrat loads, and if the file ever fails to load.
  fallback: [
    "system-ui",
    "-apple-system",
    "Segoe UI",
    "Roboto",
    "Helvetica Neue",
    "Arial",
    "sans-serif",
  ],
});
