// src/lib/utils.ts
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * Composes conditional classes and resolves Tailwind conflicts.
 * Overwrites the `export { cn } from "cn"` generated by `shadcn init`: this project
 * stays on clsx + tailwind-merge, which is what frontend.md requires.
 */
export function cn (...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
